### ISSUE TITLE
Request For Comment

### ISSUE THREAD

**Issue by tleef** [tleef/bliss#6]
### What is Bliss?

Bliss is a data validation library. It can be used to assert that your data is the expected type as well as other properties of that data e.g. `:length` in the case of a `String` or an `Array`.

Many types can be validated with Bliss including but not limited to

- [x] Any
- [x] String
- [x] #7
- [x] #9
- [x] #13
- [x] #15
- [x] #22
- [x] #18
- [x] #20
- [x] #24
- [x] #26

> Note: Some of these types are not implemented at the time of writing

You may also extend Bliss with your own custom types. All you need to do is `use Bliss.Type` and implement a `check/3` function which gets called when validating some input against your custom type. One common example of defining your own custom type is structs.

Elixir gives us the ability to define structs which are just maps with a predefined set of atoms as keys where each key may have a default value. This is helpful as it ensures that the keys in our struct are atoms and that there are no additional keys that we don't know about. At runtime, however, we don't get any assurances that the values in our struct are what we expect them to be. To be sure, we must make these assertions ourselves.

This is where Bliss can help. It gives us a simple way of defining a struct as well as describing its values and validating those values at runtime.

_Example_
```elixir
defmodule Money do
  use Bliss.Struct

  schema do
    field :amount, :float, [:required, :parse, :positive]
    field :currency, :string, [:required, default: "USD", enum: ["USD", "EUR", "BTC"]]
  end
end

defmodule Book do
  use Bliss.Struct

  schema do
    field :title, :string, [:required]
    field :author, :string, [:required, default: "Unknown"]
    field :description, :string
    field :price, Money, [:required, :cast]
  end
end
```

In the above example, we are defining two structs by employing `use Bliss.Struct` with a `schema` block where `fields` are defined. When you define a struct in this way, `Bliss.Struct` will call `defstruct` for you and create an Elixir struct with defaults when given. In addition, it will define a `validate` function on your struct that can be used to validate values at runtime.

The `validate` function uses the fields defined in the `schema` block to automatically assert the type of each value as well as assert that the given rules are being followed. 

Each `field` takes a `name`, `type` and optional `rules`. The `name` must be an atom. The `type` must also be an atom and can either be a built-in type or a custom type e.g. the `Money` type used by the `:price` field in the example above. The `rules` vary depending on the `type` given. See below for a list of all rules per type.

#### Bliss.Any
- `:default` - If the input is `nil`, sets input to given value
- `:required` - Asserts that input is not `nil`
- `:equals` - Asserts that input is equal to given value
- `:enum` - Asserts that input is in list of given values

#### Bliss.String
- `:trim` - Trims any leading or trailing whitespace from the input
- `:length` - Asserts that input has the given length
- `:min` - Asserts that input length is greater than or equal to the given length
- `:max` - Asserts that input length is less than or equal to the given length

#### Bliss.Integer
- `:parse` - if input is a string, try to parse it to an integer
- `:trunc` - if input is a float, truncate it to an integer
- `:min` - assert that input is greater than or equal to given value
- `:max` - assert that input is less than or equal to given value
- `:greater_than` - assert that input is greater than given value
- `:less_than` - assert that input is less than given value

#### Bliss.Float
- `:parse` - if input is a string, try to parse it to a float
- `:allow_int` - if input is an integer, convert it to a float
- `:min` - assert that input is greater than or equal to given value
- `:max` - assert that input is less than or equal to given value
- `:greater_than` - assert that input is greater than given value
- `:less_than` - assert that input is less than given value

#### Bliss.Boolean
- `:parse` - if input is a string, try to parse it to a boolean

#### Bliss.Atom
- `:parse` - if input is a string, try to parse it to an atom

#### Bliss.Struct
- `:cast` - If the input is a `map`, try to cast it to the given struct

> Note: These are all of the rules at the time of writing but there will be more. Also, the rules for `Bliss.Any` may be used for all other types as well since every type is implicitly a `Bliss.Any`

Rules can be grouped into two main categories, "mutations" and "queries", where mutations may update the input while queries only make assertions about the input. Within the category of mutations, there are two sub-categories, "type-changing" and "type-preserving", where type-changing mutations may change the input type while type-preserving mutations will not. See below for examples of each category.

#### Queries
- `:required`
- `:equals`
- `:length`

#### Mutations
- Type-Changing
  - `:default`
  - `:cast`
- Type-Preserving
  - `:trim`

Because of the varied nature of the different categories of rules, the order in which they are applied matters. For example, given an input of `nil`, when applying `:required` and `:default`, if you apply `:required` first, you will get an error however, if you apply `:default` first, you may not. For this reason, the order in which rules are applied is determined by Bliss, not the order given to the `validate` or `field` functions.

### How to validate

Validating data is as simple as calling `validate` on the type that you would like to assert and passing in optional rules. The validate function will return either `{:ok, value}` or `{:error, errors}`.

_Examples_
```elixir
Bliss.String.validate("hello world")
{:ok, "hello world"}

Bliss.String.validate("oops", length: 5)
{:error,
 [
   %Bliss.Error{
     code: "invalid_string",
     message: "input does not have correct length",
     path: ["."]
   }
 ]}
 
Bliss.String.validate(nil, [:required, default: "sleepy bear"])
{:ok, "sleepy bear"}

Book.validate(%{title: "I <3 Elixir", price: %{amount: "1.00"}})
{:error,
 [
   %Bliss.Error{
     code: "invalid_type",
     message: "input is not a Book",
     path: ["."]
   }
 ]}
 
Book.validate(%{title: "I <3 Elixir", price: %{amount: "1.00"}}, [:cast])
{:ok,
 %Book{
   author: "Unknown",
   description: nil,
   price: %Money{amount: "1.00", currency: "USD"},
   title: "I <3 Elixir"
 }}
```

**Comment by considine** [comment]
**General** 

This is very fluent, and I'd argue more expressive than Joi, my benchmark (by virtue of Elixir syntax.

**Notes**
* It still might make sense to have the `atLeast` `atMost` operators for integers unless it's a pain in the neck. I know these are syntactic sugar entirely, but sometimes it makes more sense to read validation this way depending on the problem. 
* Should booleans have options for nullable or not?
* I looked at my 25 usages of Joi (and a few `request-validator` :roll_eyes: ) and one operator that I use frequently which is probably out of scope of v1 is `alternatives` FWIW 
* Return syntax makes sense entirely

All in all even without my suggestions would immediately use this for all Phoenix API projects

**Comment by tleef** [comment]
**Alternatives**
I 100% agree, definitely want to have something similar to Joi `alternatives`. 

There is `alternatives.try()` which is similar to `z.union()` from Zod. I personally like the name "union" better to describe this behavior so I thought about calling it a `Bliss.Union`. 

There is also `alternatives.conditional()` which is one of my favorites from Joi. For this, I think we can just call it a `Bliss.Conditional`

For both of these, I think they will need to wait until after v1 because I'm not sure what the syntax should look like yet. Especially for `Bliss.Conditional`.

**Booleans**
As it is right now, a `Bliss.Boolean` can be `nil`. I think you are asking if that is the correct behavior or if it should just default to `false`.

While I agree that `false` is often a sensible default, I prefer to keep the current behavior for a few of reasons.

1. No special cases (or as few as possible). Having special logic for some types and not others leads to a more difficult learning curve, more gotchas, and ultimately more bugs. I think about [the empty string issue](https://joi.dev/api/?v=17.6.0#string) with Joi.
2. In some scenarios there may be a semantic difference between `false` and `nil` which I don't think Bliss should prohibit.
3. As a general rule, I think Bliss should be thought of as a tool. It is meant to work for you, but it doesn't think for you. You need to be explicit about what you want Bliss to do. In this case, that means setting the `:required` flag during validation.

**Integers**
I'm not clear what you mean by 
> It still might make sense to have the `atLeast` `atMost` operators

Are you saying it might make sense to rename `:min` to `:at_least` and `:max` to `:at_most`? I don't mind this idea. 

I went with `:min` and `:max` because those names are used by other types so I thought it might be a bit easier to remember. We could also consider making `:at_least` and `:at_most` aliases for `:min` and `:max`. 

Currently there are no aliases in the rule sets though and I think we should be careful before introducing them. My gut feeling here is that aliases add a larger surface area of code to maintain for not much benefit.

**Comment by tleef** [comment]
Closing, the api and functionality of v1.0.0 has been finalized.
